[package]

version = "0.1.0"

category = "isaaclab"
readme = "README.md"

title = "IL MAV Carry"
author = "Aerial Manipulation Lab"
maintainer = "Aerial Manipulation Lab"
description = "Imitation learning for cooperative aerial manipulation in Isaac Lab"
repository = "https://github.com/Aerial-Manipulation-Lab/IL_cooperative_aerial_manipulation_ext"
keywords = ["extension", "isaaclab", "aerial-manipulation", "imitation-learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "IL_mav_carry_ext"
