from __future__ import annotations

import math

import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg
from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import JointWrenchSensorCfg
from isaaclab.utils.configclass import (
    configclass,  # explicit: isaaclab.utils lazy-exports this name and it can be shadowed by the submodule
)
from isaaclab.utils.noise import GaussianNoiseCfg

import IL_mav_carry_ext.tasks.managerbased.mdp as mdp
from IL_mav_carry_ext.assets import FLYCRANE_CFG


# Isaac Lab 3.0 folded AdditiveGaussianNoiseCfg into GaussianNoiseCfg(operation="add")
def Gnoise(**kwargs):
    return GaussianNoiseCfg(operation="add", **kwargs)


# Define the scene configuration


@configclass
class CarryingSceneCfg(InteractiveSceneCfg):
    """Configuration for multi-drone lifting system"""

    # Ground-plane
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())

    # Lights
    distant_light = AssetBaseCfg(
        prim_path="/World/Light", spawn=sim_utils.DistantLightCfg(intensity=3000.0, color=(0.75, 0.75, 0.75))
    )

    # Drones
    robot: ArticulationCfg = FLYCRANE_CFG.replace(prim_path="{ENV_REGEX_NS}/flycrane")

    joint_forces = JointWrenchSensorCfg(prim_path="{ENV_REGEX_NS}/flycrane")


# MDP settings


@configclass
class ApproachPoseCommandsCfg:
    """A min-jerk approach to a random payload pose."""

    pose_command = mdp.ApproachPoseCommandCfg(
        asset_name="robot",
        body_name="load_odometry_sensor_link",
        debug_vis=True,
        ramp_duration=3.0,  # min-jerk ramp: never more than a gentle move away
        ranges=mdp.ApproachPoseCommandCfg.Ranges(
            pos_x=(-1.0, 1.0),
            pos_y=(-1.0, 1.0),
            pos_z=(0.5, 1.5),
            roll=(-math.pi / 4, math.pi / 4),
            pitch=(-math.pi / 4, math.pi / 4),
            yaw=(-math.pi, math.pi),
        ),
    )


@configclass
class FigureEightCommandsCfg:
    """A random figure eight, from wherever the payload starts."""

    pose_command = mdp.FigureEightCommandCfg(
        asset_name="robot",
        body_name="load_odometry_sensor_link",
        debug_vis=True,
        ranges=mdp.FigureEightCommandCfg.Ranges(
            amplitude=(1.0, 2.5),  # the thesis's a4 to a2 size
            acceleration=(0.5, 4.5),  # up to past the a4's 4.1 m/s^2
            yaw_rate=(-0.3, 0.3),  # both ways round, past the thesis's 0.25 rad/s
        ),
    )


@configclass
class ActionsCfg:
    """Actions for the flycrane.

    The ActionTerm is responsible for processing the actions and applying them to the robot,
    based on the waypoint given that will later be a trajectory generated by the policy."""

    low_level_action: mdp.LowLevelActionCfg = mdp.LowLevelActionCfg(
        asset_name="robot",
        body_name="Falcon.*rotor_.*",
        debug_vis=False,
        control_mode="geometric",  # what the MPC teacher outputs: p, v, a per drone
    )


@configclass
class ObservationsCfg:
    """Observations for the flycrane."""

    @configclass
    class PolicyCfg(ObsGroup):
        """Observation terms for the policy."""

        # payload and drone states
        payload_position = ObsTerm(func=mdp.payload_position, noise=Gnoise(std=0.003))
        payload_orientation = ObsTerm(func=mdp.payload_orientation, noise=Gnoise(std=0.01))
        payload_linear_velocities = ObsTerm(func=mdp.payload_linear_velocities, noise=Gnoise(std=0.01))
        payload_angular_velocities = ObsTerm(func=mdp.payload_angular_velocities, noise=Gnoise(std=0.02))

        drone_positions = ObsTerm(func=mdp.drone_positions, noise=Gnoise(std=0.003))
        drone_orientations = ObsTerm(func=mdp.drone_orientations, noise=Gnoise(std=0.01))
        drone_linear_velocities = ObsTerm(func=mdp.drone_linear_velocities, noise=Gnoise(std=0.01))
        drone_angular_velocities = ObsTerm(func=mdp.drone_angular_velocities, noise=Gnoise(std=0.02))

        # error to the command: the reference pose now
        payload_positional_error = ObsTerm(
            func=mdp.payload_positional_error, params={"command_name": "pose_command"}, noise=Gnoise(std=0.003)
        )
        payload_orientation_error = ObsTerm(
            func=mdp.payload_orientation_error, params={"command_name": "pose_command"}, noise=Gnoise(std=0.01)
        )

        # imitation terms: what the MPC teacher sees, in a form a uniform
        # per-drone student can use (appended, so the columns above keep
        # their place). No noise on the reference: it is a command, not a
        # measurement.
        drone_pos_rel_payload = ObsTerm(func=mdp.payload_drone_rpos, noise=Gnoise(std=0.003))
        drone_cable_dir = ObsTerm(func=mdp.drone_cable_dir, noise=Gnoise(std=0.01))
        payload_ref_horizon = ObsTerm(func=mdp.payload_ref_horizon, params={"command_name": "pose_command"})

        # action terms

        def __post_init__(self):
            self.enable_corruption = False  # for adding noise to the observations
            self.concatenate_terms = True

    # Observation group
    policy: PolicyCfg = PolicyCfg()


@configclass
class EventCfg:
    """Events for the flycrane.

    Resetting states on resets, disturbances, etc.
    """

    reset_all = EventTerm(func=mdp.reset_scene_to_default, mode="reset")

    reset_base = EventTerm(
        func=mdp.reset_root_state_uniform,
        mode="reset",
        params={
            "pose_range": {
                "x": (-1.0, 1.0),
                "y": (-1.0, 1.0),
                "z": (0.5, 1.5),
                "roll": (-0, 0),
                "pitch": (-0, 0),
                "yaw": (-math.pi, math.pi),
            },
            "velocity_range": {
                "x": (-0.0, 0.0),
                "y": (-0.0, 0.0),
                "z": (-0.0, 0.0),
                "roll": (-0.0, 0.0),
                "pitch": (-0.0, 0.0),
                "yaw": (-0.0, 0.0),
            },
        },
    )

    base_external_force_torque = EventTerm(
        func=mdp.apply_external_force_torque,
        mode="reset",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names=".*"),
            "force_range": (0.0, 0.0),
            "torque_range": (-0.0, 0.0),
        },
    )


@configclass
class TerminationsCfg:
    """Terminal conditions for the flycrane.

    When the payload reaches a certain height, etc."""

    # end when sim times out. Named `success` because Isaac Lab's recorder marks
    # an episode successful only through a termination term of exactly that
    # name (and overwrites any flag set by hand right before it exports). So
    # "success" means the episode ran to its end without crashing or a failed
    # solve; whether it also ended close to the goal is for the dataset loader
    # to decide from the recorded states.
    success = DoneTerm(func=mdp.time_out, time_out=True)

    mpc_failed = DoneTerm(func=mdp.mpc_failed)

    # end on touching the ground, the one thing a flycrane can hit (self-collisions are off, envs filtered).
    # From heights, not a contact sensor: its PhysX reading can outlive a reset and end every restart.
    # 0.2 m for the drones, so one tilted onto an arm is caught too
    falcon_fly_low = DoneTerm(func=mdp.falcon_fly_low, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.2})
    payload_fly_low = DoneTerm(
        func=mdp.payload_fly_low, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.1}
    )

    angle_drones_cable = DoneTerm(
        func=mdp.cable_angle_drones_cos, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.0}
    )
    angle_load_cable = DoneTerm(
        func=mdp.cable_angle_payload_cos, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": -math.sqrt(2) / 2}
    )

    cables_collide = DoneTerm(
        func=mdp.cable_collision, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.2, "num_points": 10}
    )

    drones_collide = DoneTerm(func=mdp.drone_collision, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 0.2})

    bounding_box = DoneTerm(func=mdp.bounding_box, params={"asset_cfg": SceneEntityCfg("robot"), "threshold": 5.0})


@configclass
class FlycraneEnvCfg(ManagerBasedRLEnvCfg):
    """The flycrane and its NMPC teacher; each task adds its `commands` and episode length."""

    scene: CarryingSceneCfg = CarryingSceneCfg(num_envs=1, env_spacing=4.0)
    actions: ActionsCfg = ActionsCfg()
    observations: ObservationsCfg = ObservationsCfg()
    events: EventCfg = EventCfg()
    rewards = None
    terminations: TerminationsCfg = TerminationsCfg()

    def __post_init__(self):
        """Post initialization."""
        # general settings
        self.decimation = 3
        # simulation settings
        self.sim.dt = 0.0033333333333333335
        self.sim.render_interval = self.decimation
        self.sim.gravity = (0.0, 0.0, -9.8066)


@configclass
class ApproachPoseEnvCfg(FlycraneEnvCfg):
    """Carry the payload to a random pose."""

    commands: ApproachPoseCommandsCfg = ApproachPoseCommandsCfg()

    def __post_init__(self):
        super().__post_init__()
        # the 3 s ramp plus the ~7 s the MPC takes to settle the swinging payload
        # (measured with check_student_obs.py --episode_length 20: flat from ~10 s),
        # so episodes hold the whole manoeuvre but little idle hover
        self.episode_length_s = 10.0


@configclass
class FigureEightEnvCfg(FlycraneEnvCfg):
    """Carry the payload along a random figure eight."""

    commands: FigureEightCommandsCfg = FigureEightCommandsCfg()

    def __post_init__(self):
        super().__post_init__()
        self.episode_length_s = 40.0  # the thesis's figure eight, rest to rest
        # a figure up to 5 m long from a spawn up to 1 m off the env origin, turned any way, reaches 6 m
        self.terminations.bounding_box.params["threshold"] = 7.0


@configclass
class FigureEightA2EnvCfg(FigureEightEnvCfg):
    """The thesis's figure eight: 5 x 4 m, up to 2.4 m/s and 2 m/s^2."""

    def __post_init__(self):
        super().__post_init__()
        self.commands.pose_command.csv = "figure_eight_v2_a2_yaw025.csv"


@configclass
class FigureEightA4EnvCfg(FigureEightEnvCfg):
    """The thesis's figure eight at half the size, so twice the acceleration: up to 4.1 m/s^2."""

    def __post_init__(self):
        super().__post_init__()
        self.commands.pose_command.csv = "figure_eight_v2_a4_yaw025.csv"
